spring:
  application:
    name: mclientes
  data:
    mongodb:
      #host: elmongo
      host: localhost
      port: 27017
      database: ventas
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka-server:8761/eureka/